# Generated by Django 4.2.3 on 2023-08-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0002_advertisement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
