# Generated by Django 4.2.3 on 2023-08-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0004_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='adv', verbose_name='изображения'),
            preserve_default=False,
        ),
    ]
