# Generated by Django 4.2.3 on 2023-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userreg',
        ),
    ]
